function sendCommand() {
    let command = document.getElementById("aiCommand").value;
    if (command.trim() === "") {
        alert("Please enter a command.");
        return;
    }

    // Add user message to chat
    let chatBox = document.getElementById("chatBox");
    let userMessage = document.createElement("div");
    userMessage.className = "chat-message user";
    userMessage.innerText = command;
    chatBox.appendChild(userMessage);
    chatBox.scrollTop = chatBox.scrollHeight;

    // Send request to PHP backend
    fetch('ai_process.php', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt: command }),
    })
    .then(response => response.json())
    .then(data => {
        if (data.status === 'success') {
            // Clean up the SQL query
            let sqlQuery = data.sqlQuery.trim();

            // Remove any unwanted start and finish (like 'sql' tags or extra characters)
            sqlQuery = sqlQuery.replace(/^\s*```sql|\s*```$/g, '').trim();

            // Display the SQL query generated by AI
            let aiMessage = document.createElement("div");
            aiMessage.className = "chat-message bot";
            aiMessage.innerText = sqlQuery;
            chatBox.appendChild(aiMessage);
            chatBox.scrollTop = chatBox.scrollHeight;
        } else {
            let aiMessage = document.createElement("div");
            aiMessage.className = "chat-message bot";
            aiMessage.innerText = "Error generating query.";
            chatBox.appendChild(aiMessage);
            chatBox.scrollTop = chatBox.scrollHeight;
        }
    })
    .catch(error => {
        console.error("Error:", error);
        let aiMessage = document.createElement("div");
        aiMessage.className = "chat-message bot";
        aiMessage.innerText = "Error processing request.";
        chatBox.appendChild(aiMessage);
        chatBox.scrollTop = chatBox.scrollHeight;
    });

    // Clear the input field
    document.getElementById("aiCommand").value = "";
}